name: Test

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.13'
  POETRY_VERSION: '2.4.1'

jobs:
  test:
    runs-on: ubuntu-24.04
    container:
      image: python:3.13
    strategy:
      fail-fast: false
      matrix:
        deps: [pinned, latest]
    name: Test (${{ matrix.deps }} dependencies)
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get -y install curl git libcairo2-dev nodejs graphviz

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load existing venv
        run: poetry env use system

      - name: Install pinned dependencies
        if: matrix.deps == 'pinned'
        run: poetry install --all-extras

      - name: Install latest dependencies
        if: matrix.deps == 'latest'
        run: |
          poetry install --all-extras
          pip install --upgrade $(pip list --format=freeze | cut -d= -f1 | tr '\n' ' ')

      - name: Run tests
        run: poetry run pytest -vv --cov=stormvogel --cov-report=xml tests/
